{
 "title": "Go Metrics",
 "tags": [
  "go",
  "golang"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "service_name",
    "query": "label_values(go_goroutine_count, service_name)"
   }
  ]
 },
 "panels": [
  {
   "title": "Running Goroutines",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "go_goroutine_count{service_name=~\"$service_name\"}",
     "legendFormat": "{{service_name}}"
    }
   ]
  },
  {
   "title": "Memory Used Bytes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "go_memory_used_bytes{service_name=~\"$service_name\"}",
     "legendFormat": "{{service_name}}"
    }
   ]
  },
  {
   "title": "Memory GC Goal Bytes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "go_memory_gc_goal_bytes{service_name=~\"$service_name\"}",
     "legendFormat": "{{service_name}}"
    }
   ]
  },
  {
   "title": "Allocated Memory Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "rate(go_memory_allocated_bytes_total{service_name=~\"$service_name\"}[1m])",
     "legendFormat": "{{service_name}}"
    }
   ]
  },
  {
   "title": "Allocation Count Rate (Objects/sec)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(go_memory_allocations_total{service_name=~\"$service_name\"}[1m])",
     "legendFormat": "{{service_name}}"
    }
   ]
  },
  {
   "title": "Processor Limit (GOMAXPROCS)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "go_processor_limit{service_name=~\"$service_name\"}",
     "legendFormat": "{{service_name}}"
    }
   ]
  }
 ]
}