// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"go-flashsale-mini-kafka-basic/inventory-service/internal/adapter/inbound/grpc"
	"go-flashsale-mini-kafka-basic/inventory-service/internal/adapter/outbound/postgres"
	redis2 "go-flashsale-mini-kafka-basic/inventory-service/internal/adapter/outbound/redis"
	"go-flashsale-mini-kafka-basic/inventory-service/internal/application/usecase"
	"github.com/go-kratos/kratos/v2/log"
	"github.com/jmoiron/sqlx"
	"github.com/redis/go-redis/v9"
)

import (
	_ "github.com/lib/pq"
)

// Injectors from wire.go:

func initApp(db *sqlx.DB, rdb *redis.Client, logger log.Logger) (*grpc.InventoryServer, error) {
	redisPort := redis2.NewRedisPort(rdb)
	outboxPort := postgres.NewOutboxRepo(db)
	reserveStockUsecase := usecase.NewReserveStockUsecase(redisPort, outboxPort)
	releaseStockUsecase := usecase.NewReleaseStockUsecase(redisPort)
	inventoryServer := grpc.NewInventoryServer(reserveStockUsecase, releaseStockUsecase)
	return inventoryServer, nil
}
