// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"go-flashsale-mini-kafka-basic/payment-service/internal/adapter/inbound/grpc"
	"go-flashsale-mini-kafka-basic/payment-service/internal/adapter/outbound/postgres"
	"go-flashsale-mini-kafka-basic/payment-service/internal/application/usecase"
	"github.com/jmoiron/sqlx"
)

import (
	_ "github.com/lib/pq"
)

// Injectors from wire.go:

func InitializePaymentServer(db *sqlx.DB) *grpc.PaymentServer {
	paymentRepository := postgres.NewPaymentRepository(db)
	processPaymentUsecase := usecase.NewProcessPaymentUsecase(paymentRepository)
	paymentServer := grpc.NewPaymentServer(processPaymentUsecase)
	return paymentServer
}
