// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"go-flashsale-mini-kafka-basic/product-service/internal/adapter/inbound/grpc"
	"go-flashsale-mini-kafka-basic/product-service/internal/adapter/outbound/postgres"
	"go-flashsale-mini-kafka-basic/product-service/internal/application/usecase"
	"github.com/go-kratos/kratos/v2/log"
	"github.com/jmoiron/sqlx"
)

import (
	_ "github.com/lib/pq"
)

// Injectors from wire.go:

func initApp(db *sqlx.DB, logger log.Logger) (*grpc.ProductServer, error) {
	productRepository := postgres.NewProductRepo(db)
	listFlashSaleProductsUsecase := usecase.NewListFlashSaleProductsUsecase(productRepository)
	productServer := grpc.NewProductServer(listFlashSaleProductsUsecase)
	return productServer, nil
}
